/*
 * Copyright (c) 2025, Atsushi Ogawa
 * All rights reserved.
 *
 * This software is licensed under the BSD License.
 * See the LICENSE_BSD file for details.
 */

#include "resource.h"

static const ACCEL default_accel[] = {
	{FVIRTKEY | FCONTROL | FNOINVERT, 'A', ID_SELECT_ALL},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'B', ID_BOX_SELECT},
	{FVIRTKEY | FSHIFT | FCONTROL | FNOINVERT, 'C', ID_GRID_COPY_CSV},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'D', ID_DOWNLOAD},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'E', ID_EXPLAIN_RUN},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'F', ID_SEARCH},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'H', ID_REPLACE},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'L', ID_SQL_LOG},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'N', ID_FILE_NEW},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'O', ID_FILE_OPEN},
	{FVIRTKEY | FCONTROL | FNOINVERT, VK_F4, ID_FILE_CLOSE},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'P', ID_FILE_PRINT},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'Q', ID_NEXT_PANE},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'R', ID_SQL_RUN},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'S', ID_FILE_SAVE},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'U', ID_TO_LOWER},
	{FVIRTKEY | FSHIFT | FCONTROL | FNOINVERT, 'U', ID_TO_UPPER},

	{FVIRTKEY | FCONTROL | FNOINVERT, 'C', ID_EDIT_COPY},
	{FVIRTKEY | FCONTROL | FNOINVERT, VK_INSERT, ID_EDIT_COPY},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'X', ID_EDIT_CUT},
	{FVIRTKEY | FSHIFT | FNOINVERT, VK_DELETE, ID_EDIT_CUT},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'V', ID_EDIT_PASTE},
	{FVIRTKEY | FSHIFT | FNOINVERT, VK_INSERT, ID_EDIT_PASTE},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'Z', ID_EDIT_UNDO},
	{FVIRTKEY | FALT | FNOINVERT, VK_BACK, ID_EDIT_UNDO},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'Y', ID_EDIT_REDO},

	{FVIRTKEY | FNOINVERT, VK_F2, ID_JUMP_BOOK_MARK},
	{FVIRTKEY | FCONTROL | FNOINVERT, VK_F2, ID_SET_BOOK_MARK},
	{FVIRTKEY | FSHIFT | FNOINVERT, VK_F2, ID_JUMP_BOOK_MARK_BACK},
	{FVIRTKEY | FSHIFT | FCONTROL | FNOINVERT, VK_F2, ID_CLEAR_ALL_BOOK_MARK},
	{FVIRTKEY | FNOINVERT, VK_F3, ID_SEARCH_NEXT},
	{FVIRTKEY | FALT | FNOINVERT, VK_F3, ID_CLEAR_SEARCH_TEXT},
	{FVIRTKEY | FSHIFT | FNOINVERT, VK_F3, ID_SEARCH_PREV},
	{FVIRTKEY | FCONTROL | FNOINVERT, VK_F3, ID_SEARCH_SELECTED},
	{FVIRTKEY | FNOINVERT, VK_F6, ID_NEXT_PANE},
	{FVIRTKEY | FSHIFT | FNOINVERT, VK_F6, ID_PREV_PANE},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'W', ID_SWITCH_VIEW},
	{FVIRTKEY | FCONTROL | FNOINVERT, 'G', ID_LINE_JUMP},

	{FVIRTKEY | FCONTROL | FNOINVERT, VK_F6, ID_NEXT_DOC},
	{FVIRTKEY | FSHIFT | FCONTROL | FNOINVERT, VK_F6, ID_PREV_DOC},

	{FVIRTKEY | FNOINVERT, VK_INSERT, ID_TOGGLE_OVERWRITE},

	{FVIRTKEY | FCONTROL | FNOINVERT, '1', ID_ACTIVE_SQL_EDITOR},
	{FVIRTKEY | FCONTROL | FNOINVERT, '2', ID_ACTIVE_SQL_RESULT},
	{FVIRTKEY | FCONTROL | FNOINVERT, '3', ID_ACTIVE_RESULT_GRID},

	{FVIRTKEY | FNOINVERT, VK_TAB, ID_EDIT_INDENT},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_TAB, ID_EDIT_INDENT_REV},

	{FVIRTKEY | FNOINVERT, VK_LEFT, ID_CHAR_LEFT},
	{FVIRTKEY | FNOINVERT, VK_RIGHT, ID_CHAR_RIGHT},
	{FVIRTKEY | FNOINVERT, VK_UP, ID_LINE_UP},
	{FVIRTKEY | FNOINVERT, VK_DOWN, ID_LINE_DOWN},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_LEFT, ID_WORD_LEFT},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_RIGHT, ID_WORD_RIGHT},
	{FVIRTKEY | FNOINVERT, VK_HOME, ID_LINE_START},
	{FVIRTKEY | FNOINVERT, VK_END, ID_LINE_END},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_HOME, ID_DOCUMENT_START},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_END, ID_DOCUMENT_END},
	{FVIRTKEY | FNOINVERT, VK_PRIOR, ID_PAGE_UP},
	{FVIRTKEY | FNOINVERT, VK_NEXT, ID_PAGE_DOWN},

	{FVIRTKEY | FNOINVERT | FSHIFT, VK_LEFT, ID_CHAR_LEFT_EXTEND},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_RIGHT, ID_CHAR_RIGHT_EXTEND},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_UP, ID_LINE_UP_EXTEND},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_DOWN, ID_LINE_DOWN_EXTEND},
	{FVIRTKEY | FNOINVERT | FCONTROL | FSHIFT, VK_LEFT, ID_WORD_LEFT_EXTEND},
	{FVIRTKEY | FNOINVERT | FCONTROL | FSHIFT, VK_RIGHT, ID_WORD_RIGHT_EXTEND},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_HOME, ID_LINE_START_EXTEND},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_END, ID_LINE_END_EXTEND},
	{FVIRTKEY | FNOINVERT | FCONTROL | FSHIFT, VK_HOME, ID_DOCUMENT_START_EXTEND},
	{FVIRTKEY | FNOINVERT | FCONTROL | FSHIFT, VK_END, ID_DOCUMENT_END_EXTEND},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_PRIOR, ID_PAGE_UP_EXTEND},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_NEXT, ID_PAGE_DOWN_EXTEND},

	{FVIRTKEY | FNOINVERT | FCONTROL, VK_UP, ID_SCROLL_UP},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_DOWN, ID_SCROLL_DOWN},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_PRIOR, ID_SCROLL_PAGE_UP},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_NEXT, ID_SCROLL_PAGE_DOWN},

	{FVIRTKEY | FNOINVERT, VK_DELETE, ID_EDIT_DELETE},
	{FVIRTKEY | FNOINVERT, VK_BACK, ID_EDIT_BACKSPACE},
	{FVIRTKEY | FNOINVERT, VK_ESCAPE, ID_KEYWORD_COMPLETION},
	{FVIRTKEY | FNOINVERT | FSHIFT, VK_ESCAPE, ID_KEYWORD_COMPLETION_REV},
	{FVIRTKEY | FNOINVERT | FCONTROL, VK_SPACE, ID_CODE_ASSIST_ON},
};

