//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// psqledit.rc で使用
//
#define IDC_BTN_BOTTOM                  3
#define IDALLYES                        4
#define IDALLNO                         5
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PSQLEDTYPE                  129
#define IDD_LOGIN                       130
#define IDD_CANCEL_DLG                  131
#define IDD_SQL_LOG_DLG                 132
#define IDD_SEARCH_DLG                  133
#define IDD_CONNECT_INFO_DLG            134
#define IDD_REPLACE_DLG                 135
#define IDD_FILE_FORMAT_DLG             137
#define IDD_OPT_EDITOR                  138
#define IDD_OPT_FUNC                    139
#define IDD_OPT_SETUP                   140
#define IDR_DUMMY                       142
#define IDD_SQL_LIBRARY_DLG             144
#define IDI_PARENT_FOLDER               145
#define IDI_FOLDER                      146
#define IDD_DOWNLOAD_DLG                150
#define IDR_EDIT_MENU                   151
#define IDR_RESULT_MENU                 152
#define IDR_GRID_MENU                   153
#define IDD_ACCELERATOR_DLG             155
#define IDR_TAB_MENU                    156
#define IDD_LINE_JUMP_DLG               157
#define IDR_GRID_CALC_MENU              158
#define IDD_PRINT_DLG                   159
#define IDD_SHORTCUT_SQL_LIST_DLG       160
#define IDD_SHORTCUT_SQL_DLG            161
#define IDD_SHORTCUT_KEY_DLG            162
#define IDD_OPT_EDITOR2                 163
#define IDD_OPT_FUNC2                   164
#define IDD_OPT_GRID                    166
#define IDD_BIND_PARAM_EDITOR_DLG       170
#define IDD_GRID_SORT_DLG               175
#define IDD_NAME_INPUT_DLG              186
#define IDD_QUERY_CLOSE_DLG             188
#define IDD_SHOW_CLOB_DLG               189
#define IDD_SQL_LOG_FILE_DLG            207
#define IDR_OBJECTBAR_FILTER_MENU       209
#define IDD_GRID_FILTER_DLG             217
#define IDC_COMBO_PRINTER               1002
#define IDC_EDIT_SPACE_LEFT             1003
#define IDC_EDIT_SPACE_RIGHT            1004
#define IDC_EDIT_SPACE_TOP              1005
#define IDC_EDIT_SPACE_BOTTOM           1007
#define IDC_CHECK_PRINT_TITLE           1008
#define IDC_CHECK_PRINT_PAGE            1010
#define IDC_CHECK_PRINT_ROW_NUM         1011
#define IDC_CHECK_PRINT_DATE            1012
#define IDC_COMBO_KANJI_CODE            1013
#define IDC_COMBO_LINE_TYPE             1015
#define IDC_STATIC_PAGE_INFO            1019
#define IDC_STATIC_FONT                 1025
#define IDC_STATIC_FONT_SIZE            1030
#define IDC_PRINTER_SETUP               1032
#define IDC_SET_FONT                    1034
#define IDC_CHECK_SHOW_SPACE            1060
#define IDC_CHECK_ROW_COPY_AT_NO_SEL    1071
#define IDC_CHECK_SHOW_BRACKETS_BOLD    1076
#define IDC_COMBO_SEARCH_TEXT           1900
#define ID_BTN_NEXT                     1901
#define ID_BTN_PREV                     1902
#define IDC_CHECK_DISTINCT_LWR_UPR      1903
#define IDC_CHECK_REGEXP                1904
#define IDC_CHECK_DISTINCT_WIDTH_ASCII  1905
#define IDC_COMBO_REPLACE_TEXT          1905
#define ID_BTN_REPLACE                  1906
#define ID_BTN_REPLACE_ALL              1907
#define IDC_RADIO_SELECTED_AREA         1908
#define IDC_RADIO_ALL                   1909
#define IDC_CHECK_DISTINCT_WIDTH_ASCII2 1910
#define IDC_EDIT_DATA                   1935
#define IDC_EDIT_FILTER                 1937
#define IDC_COMBO_USER                  1966
#define IDC_STATIC_ICON                 1981
#define IDC_EDIT_MAKE_SELECT_ALIAS_NAME 1986
#define IDC_EDIT_USER                   2000
#define IDC_EDIT_PASS                   2002
#define IDC_STATIC0                     2003
#define IDC_EDIT_HOST                   2004
#define IDC_STATIC1                     2005
#define IDC_EDIT_DB_NAME                2006
#define IDC_STATIC2                     2006
#define IDC_EDIT_PORT_NO                2007
#define IDC_EDIT_PORT                   2008
#define IDC_LIST1                       2009
#define IDC_EDIT_OPTION                 2010
#define IDC_EDIT_SQL_STMT_STR           2011
#define IDC_EDIT_CONNECT_NAME           2011
#define IDC_EDIT_NAME                   2012
#define IDC_EDIT_SHORTCUT_KEY           2013
#define IDC_CHECK_MAKE_SELECT_ADD_ALIAS_NAME 2013
#define IDC_BTN_UP                      2014
#define IDC_CHECK_REFRESH_TABLE_LIST_AFTER_DDL 2014
#define IDC_EDIT_CATEGORY               2015
#define IDC_EDIT_FILE_NAME              2017
#define IDC_EDIT_NEW_KEY                2018
#define IDC_BTN_DOWN                    2020
#define IDC_BTN_DEL                     2024
#define IDC_BTN_DEL2                    2025
#define IDC_BTN_COPY                    2025
#define IDC_BTN_ADD                     2026
#define IDC_BTN_MODIFY                  2027
#define IDC_EDIT_PASSWD                 2028
#define IDC_BTN_DELETE                  2030
#define IDC_STATIC_URL                  2031
#define IDC_CHECK_SQL_RUN_SELECTED_AREA 2032
#define IDC_EDIT_TABSTOP                2036
#define IDC_EDIT_INITIAL_DIR            2037
#define IDC_EDIT_SQL_LIB_DIR            2038
#define IDC_CHECK_SHOW_LINE_FEED        2040
#define IDC_EDIT_MAX_MSG_ROW            2041
#define IDC_CHECK_SHOW_TAB              2042
#define IDC_EDIT_MAX_MRU                2045
#define IDC_CHECK_DOWNLOAD_COLUMN_NAME  2046
#define IDC_BTN_TEXT_COLOR              2047
#define IDC_BTN_KEYWORD_COLOR           2048
#define IDC_CHECK_MAKE_SELECT_SQL_USE_SEMICOLON 2049
#define IDC_BTN_KEYWORD2_COLOR          2050
#define IDC_CHECK_IGNORE_SQL_ERROR      2051
#define IDC_BTN_COMMENT_COLOR           2052
#define IDC_BTN_BG_COLOR                2053
#define IDC_CHECK_TAB_CLOSE_AT_MCLICK   2053
#define IDC_CHECK_ADJUST_COL_WIDTH_AFTER_SELECT 2054
#define IDC_BTN_PEN_COLOR               2055
#define IDC_CHECK_TAB_CREATE_AT_DBLCLICK 2056
#define IDC_CHECK_RECEIVE_ASYNC_NOTIFY  2060
#define IDC_CHECK_SQL_LOGGING           2061
#define IDC_BTN_QUOTE_COLOR             2062
#define IDC_CHECK_AUTO_COMMIT           2063
#define IDC_BTN_DEFAULT_COLOR           2064
#define IDC_BTN_INITIAL_DIR             2065
#define IDC_CHECK_SHOW_ROW_NUM          2066
#define IDC_CHECK_TAB_DRAG_MOVE         2066
#define IDC_BTN_SQL_LIB_DIR             2070
#define IDC_CHECK_CLOSE_BTN_ON_TAB      2071
#define IDC_CHECK_SHOW_TAB_TOOLTIP      2073
#define IDC_BTN_OK                      2075
#define IDC_BTN_BRACKET_COLOR1          2098
#define IDC_BTN_BRACKET_COLOR2          2099
#define IDC_BTN_BRACKET_COLOR3          2100
#define IDC_CHECK_SHOW_COL_NUM          2160
#define IDC_CHECK_REGISTER_SHELL        2161
#define IDC_EDIT_ROW_SPACE              2162
#define IDC_CHECK_SAVE_MODIFIED         2164
#define IDC_EDIT_CHAR_SPACE             2165
#define IDC_CHECK_COPY_LOWER_NAME       2167
#define IDC_CHECK_TAB_TITLE_IS_PATH_NAME 2168
#define IDC_CHECK_SEARCH_LOOP_MSG       2170
#define IDC_CHECK_TABLE_NAME_COMPLETION 2171
#define IDC_CHECK_COLUMN_NAME_COMPLETION 2173
#define IDC_CHECK_AUTO_INIT_TABLE_LIST  2173
#define IDC_EDIT_TOP_SPACE              2175
#define IDC_EDIT_LEFT_SPACE             2178
#define IDC_SQL_LIST                    2179
#define IDC_CHECK_SHOW_2BYTE_SPACE      2180
#define IDC_BTN_SEARCH_COLOR            2181
#define IDC_BTN_SELECTED_COLOR          2182
#define IDC_EDIT_LINE_LEN               2184
#define IDC_CHECK_AUTO_INDENT           2185
#define IDC_CHECK_TAB_AS_SPACE          2186
#define IDC_CHECK_DRAG_DROP_EDIT        2187
#define IDC_BTN_RULER_COLOR             2189
#define IDC_CHECK_SHOW_ROW_LINE         2192
#define IDC_BTN_OPERATOR_COLOR          2193
#define IDC_CHECK_IME_CARET_COLOR       2194
#define IDC_CHECK_SHOW_EDIT_ROW         2195
#define IDC_BTN_FILE_SELECT             2196
#define IDC_CHECK_SAVE_SELECT_RESULT_ONLY 2197
#define IDC_LIST_CATEGORY               2198
#define IDC_LIST_COMMAND                2200
#define IDC_LIST_ACCEL                  2201
#define IDC_BTN_DEFAULT                 2202
#define IDC_STATIC_CURRENT_MENU         2203
#define IDC_EDIT_SQL_LOG_DIR            2204
#define IDC_BTN_SQL_LOG_DIR             2205
#define IDC_STATIC_LICENSE              2207
#define IDC_STATIC_VERSION              2208
#define IDC_EDIT_LINE_NO                2211
#define IDC_EDIT_INDEX                  2220
#define IDC_CHECK_SHOW_DLG              2222
#define IDC_BTN_SHORTCUT_KEY            2223
#define IDOK2                           2224
#define IDC_CHECK_PASTE_TO_EDITOR       2225
#define IDC_STATIC_MAX_CNT              2225
#define IDC_CHECK_KEYWORD_WINDOW        2227
#define IDC_CHECK_CODE_ASSIST           2228
#define IDC_STATIC_MSG                  2232
#define IDC_BTN_GRID_BG_COLOR           2240
#define IDC_BTN_GRID_HEADER_BG_COLOR    2241
#define IDC_BTN_GRID_SELECT_COLOR       2242
#define IDC_BTN_GRID_NULL_CELL_COLOR    2243
#define IDC_BTN_GRID_LINE_COLOR         2244
#define IDC_BTN_GRID_TEXT_COLOR         2245
#define IDC_BTN_GRID_MARK_COLOR         2246
#define IDC_BTN_GRID_SEARCH_COLOR       2247
#define IDC_BTN_GRID_HEADER_LINE_COLOR  2248
#define IDC_LIST_COMPLETION_TYPE        2249
#define IDC_SET_LOGIN_INFO              2250
#define IDC_COMBO_SORT_KEY1             2251
#define IDC_RADIO_ORDER_ASC1            2252
#define IDC_RADIO_ORDER_DESC1           2253
#define IDC_COMBO_SORT_KEY2             2254
#define IDC_RADIO_ORDER_ASC2            2255
#define IDC_RADIO_ORDER_DESC2           2256
#define IDC_COMBO_SORT_KEY3             2257
#define IDC_RADIO_ORDER_ASC3            2258
#define IDC_RADIO_ORDER_DESC3           2259
#define IDC_COMBO_CODE_ASSIST_SORT_COLUMN 2302
#define IDC_CHECK_COL_HEADER_DBL_CLK_PASTE 2312
#define IDC_CHECK_LINE_MODE_RIGHT       2345
#define IDC_BUTTON_SEARCH               2360
#define IDC_DATETIMEPICKER1             2361
#define IDC_DATETIMEPICKER2             2362
#define IDC_COMBO_GRID_COLUMN           2407
#define ID_BTN_FILTER_RUN               2408
#define IDC_COMBO_OBJECT_LIST_FILTER_COLUMN 2410
#define IDC_EDIT_CELL_PADDING_TOP       2412
#define IDC_EDIT_CELL_PADDING_BOTTOM    2413
#define IDC_EDIT_CELL_PADDING_LEFT      2414
#define IDC_EDIT_CELL_PADDING_RIGHT     2415
#define IDC_EDIT_DBNAME                 3000
#define IDC_COMBO_INIT_OBJECT_LIST_USER 3001
#define IDC_COMBO_INIT_OBJECT_LIST_TYPE 3002
#define ID_SELECT_ALL                   32771
#define ID_EXPLAIN_RUN                  32772
#define ID_SQL_RUN                      32773
#define ID_SWITCH_VIEW                  32774
#define ID_SQL_LOG                      32775
#define ID_SET_FONT                     32776
#define ID_DOWNLOAD                     32777
#define ID_SEARCH                       32783
#define ID_SET_LOGIN_INFO               32788
#define ID_REPLACE                      32790
#define ID_OPTION                       32792
#define ID_SEARCH_NEXT                  32794
#define ID_SEARCH_PREV                  32795
#define ID_REFRESH_TABLE_LIST           32799
#define ID_VIEW_OBJECT_BAR              32800
#define ID_VIEW_OBJECT_DETAIL_BAR       32801
#define ID_GET_OBJECT_SOURCE            32803
#define ID_SAVE_HTML                    32804
#define ID_CONVERT_TO_C                 32805
#define ID_CONVERT_TO_C_UNICODE         32806
#define ID_CONVERT_TO_JAVA              32808
#define ID_CONVERT_TO_PERL              32809
#define ID_CONVERT_TO_HTML              32810
#define ID_CONVERT_FROM_C               32811
#define ID_CONVERT_FROM_JAVA            32812
#define ID_CONVERT_FROM_PERL            32813
#define ID_CONVERT_FROM_HTML            32814
#define ID_CONVERT_TO_VB                32815
#define ID_CONVERT_FROM_VB              32816
#define ID_SQL_RUN_SELECTED             32820
#define ID_FILE_SAVE_GRID_AS            32824
#define ID_CLEAR_RESULT                 32825
#define ID_EDIT_COMMENT                 32831
#define ID_DATA_EXPORT                  32833
#define ID_SQL_LIBRARY                  32834
#define ID_ALL_FILE_CLOSE               32835
#define ID_GRID_COPY_TAB                32840
#define ID_GRID_COPY_TAB_CNAME          32841
#define ID_GRID_COPY_CSV                32842
#define ID_GRID_COPY_CSV_CNAME          32843
#define ID_GRID_COPY_FIX_LEN            32844
#define ID_GRID_COPY_FIX_LEN_CNAME      32845
#define ID_EDIT_INDENT                  32850
#define ID_EDIT_INDENT_REV              32851
#define ID_TO_LOWER                     32900
#define ID_TO_UPPER                     32901
#define ID_EDIT_REVERSE_ROWS            32902
#define ID_EDIT_SORT_ROWS_ASC           32903
#define ID_EDIT_SORT_ROWS_DESC          32904
#define ID_SET_BOOK_MARK                32910
#define ID_JUMP_BOOK_MARK               32911
#define ID_JUMP_BOOK_MARK_BACK          32912
#define ID_CLEAR_ALL_BOOK_MARK          32913
#define ID_SET_SQL_BOOKMARK             32914
#define ID_RECONNECT                    32921
#define ID_ADJUST_ALL_COL_WIDTH         32936
#define ID_EQUAL_ALL_COL_WIDTH          32938
#define ID_EDIT_DELETE                  32939
#define ID_CLEAR_SEARCH_TEXT            32940
#define ID_SET_FONT_DLG_BAR             32941
#define ID_INSERT_COMMENT               32943
#define ID_DELETE_COMMENT               32944
#define ID_ACCELERATOR                  32945
#define ID_CHAR_LEFT                    32946
#define ID_CHAR_RIGHT                   32947
#define ID_CHAR_UP                      32948
#define ID_LINE_UP                      32949
#define ID_LINE_DOWN                    32950
#define ID_WORD_LEFT                    32951
#define ID_LINE_START                   32952
#define ID_LINE_END                     32953
#define ID_DOCUMENT_START               32954
#define ID_LINE_MODE_NORMAL             32955
#define ID_DOCUMENT_END                 32956
#define ID_LINE_MODE_RIGHT              32957
#define ID_LINE_MODE_LEN                32958
#define ID_CHAR_LEFT_EXTEND             32959
#define ID_CHAR_RIGHT_EXTEND            32960
#define ID_LINE_UP_EXTEND               32961
#define ID_LINE_DOWN_EXTEND             32962
#define ID_WORD_LEFT_EXTEND             32963
#define ID_WORD_RIGHT                   32964
#define ID_WORD_RIGHT_EXTEND            32966
#define ID_LINE_START_EXTEND            32967
#define ID_LINE_END_EXTEND              32968
#define ID_DOCUMENT_START_EXTEND        32969
#define ID_DOCUMENT_END_EXTEND          32970
#define ID_PAGE_UP                      32971
#define ID_PAGE_DOWN                    32972
#define ID_PAGE_UP_EXTEND               32973
#define ID_PAGE_DOWN_EXTEND             32974
#define ID_EDIT_BACKSPACE               32975
#define ID_KEYWORD_COMPLETION           32977
#define ID_KEYWORD_COMPLETION_REV       32978
#define ID_SCROLL_DOWN                  32980
#define ID_SCROLL_UP                    32981
#define ID_SCROLL_PAGE_UP               32982
#define ID_SCROLL_PAGE_DOWN             32983
#define ID_SELECT_ROW                   32984
#define ID_ACTIVE_SQL_EDITOR            32985
#define ID_ACTIVE_SQL_RESULT            32986
#define ID_ACTIVE_RESULT_GRID           32987
#define ID_BOX_SELECT                   32988
#define ID_MAKE_SELECT_SQL              32989
#define ID_MAKE_INSERT_SQL              32990
#define ID_MAKE_UPDATE_SQL              32991
#define ID_LOGFILE_OPEN                 32992
#define ID_TOGGLE_OVERWRITE             33020
#define ID_SPACE_TO_TAB                 33050
#define ID_TAB_TO_SPACE                 33051
#define ID_MAKE_SELECT_SQL_ALL          33052
#define ID_MAKE_INSERT_SQL_ALL          33053
#define ID_VIEW_TAB_BAR                 33054
#define ID_TAB_MOVE_LEFT                33055
#define ID_TAB_MOVE_RIGHT               33056
#define ID_TAB_MOVE_TOP                 33057
#define ID_TAB_MOVE_LAST                33058
#define ID_NEXT_DOC                     33059
#define ID_PREV_DOC                     33060
#define ID_FILE_LOAD_SJIS               33061
#define ID_FILE_LOAD_EUC                33062
#define ID_FILE_LOAD_JIS                33063
#define ID_SET_FILE_FORMAT              33064
#define ID_LINE_JUMP                    33065
#define ID_DISCONNECT                   33068
#define ID_SORT_TAB                     33069
#define ID_JUMP_BOOK_MARK_EXTEND        33400
#define ID_JUMP_BOOK_MARK_BACK_EXTEND   33401
#define ID_EDIT_DELETE_ROW              33414
#define ID_EDIT_DELETE_AFTER_CURSOR     33415
#define ID_LAST_EDIT_POS                33416
#define ID_EDIT_CUT_ROW                 33417
#define ID_EDIT_COPY_ROW                33418
#define ID_EDIT_PASTE_ROW               33419
#define ID_EDIT_PASTE_ROW_UP            33421
#define ID_SPLIT_START                  33451
#define ID_SPLIT_END                    33452
#define ID_SPLIT_START_EXTEND           33453
#define ID_SPLIT_END_EXTEND             33455
#define ID_FILE_LOAD_UNICODE            33456
#define ID_FILE_LOAD_UTF8               33457
#define ID_FILE_LOAD_AUTO               33458
#define ID_FILE_RELOAD                  33459
#define ID_SELECT_WORD                  33475
#define ID_EDIT_JOIN_ROW                33492
#define ID_SEARCH_SELECTED              33494
#define ID_SHORT_CUT_SQL_DUMMY          35000
#define ID_SHORT_CUT_SQL1               35001
#define ID_SHORT_CUT_SQL2               35002
#define ID_SHORT_CUT_SQL3               35003
#define ID_SHORT_CUT_SQL4               35004
#define ID_SHORT_CUT_SQL5               35005
#define ID_SHORT_CUT_SQL6               35006
#define ID_SHORT_CUT_SQL7               35007
#define ID_SHORT_CUT_SQL8               35008
#define ID_SHORT_CUT_SQL9               35009
#define ID_SHORT_CUT_SQL10              35010
#define ID_SHORTCUT_SQL                 35200
#define ID_SETUP_SHORTCUT_SQL           35201
#define ID_CODE_ASSIST_ON               35230
#define ID_OSQLGRID                     35232
#define ID_PSQLGRID_OBJECTBAR           35235
#define ID_GRID_CALC_TYPE_TOTAL         35240
#define ID_GRID_CALC_TYPE_AVE           35241
#define ID_GRID_CALC_TYPE_MAX           35242
#define ID_GRID_CALC_TYPE_MIN           35243
#define ID_GRID_CALC_TYPE_NONE          35244
#define ID_GRID_SORT                    35250
#define ID_GRID_SWAP_ROW_COL            35265
#define ID_SQL_EDITOR_MAXIMIZE          35296
#define ID_RESULT_GRID_MAXIMIZE         35297
#define ID_FILTER_CLEAR                 35298
#define ID_COPY_VALUE                   40000
#define ID_SQL_LINT                     40001
#define ID_PSQLGRID                     40003
#define ID_GRID_CREATE_INSERT_SQL       40004
#define ID_PSQLGRID_SELECTED            40005
#define ID_SEARCH_COLUMN                40006
#define ID_TAB_NAME                     40008
#define ID_EDIT_COPY_COLUMN_NAME        40009
#define ID_SHOW_GRID_DATA               40010
#define ID_GRID_FILTER_ON               40011
#define ID_GRID_FILTER_OFF              40012
#define ID_OBJECTBAR_FILTER_ADD         40014
#define ID_OBJECTBAR_FILTER_DEL         40015
#define ID_OBJECTBAR_FILTER_CLEAR       40016
#define ID_NEW_WINDOW                   40017
#define ID_CONVERT_TO_PYTHON            40018
#define ID_CONVERT_FROM_PYTHON          40019
#define ID_CONVERT_TO_JAVASCRIPT        40020
#define ID_CONVERT_FROM_JAVASCRIPT      40021
#define ID_TO_LOWER_WITHOUT_COMMENT_LITERAL 40022
#define ID_TO_UPPER_WITHOUT_COMMENT_LITERAL 40023
#define ID_40024                        40024
#define ID_GRID_CALC_COPY               40025
#define ID_GET_OBJECT_SOURCE_DETAIL_BAR 40026
#define ID_GRID_COLUMN_WIDTH            40027
#define ID_SHOW_CREDITS                 40028
#define ID_INDICATOR_SESSION_INFO       59143
#define ID_INDICATOR_CURSOR_POS         59144
#define ID_INDICATOR_FILE_TYPE          59145
#define ID_INDICATOR_GRID_CALC          59146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         3101
#define _APS_NEXT_SYMED_VALUE           500
#endif
#endif
