/*
 * Copyright (c) 2025, Atsushi Ogawa
 * All rights reserved.
 *
 * This software is licensed under the BSD License.
 * See the LICENSE_BSD file for details.
 */

#ifndef __OCTRL_MSG_H_INCLUDED__
#define __OCTRL_MSG_H_INCLUDED__

// WM_APP + 0x100番台は，ocilibで使用

// EditCtrl
#define EDIT_CTRL_MSG_BASE			WM_APP + 0x0200

#define EC_WM_LBUTTONDBLCLK			EDIT_CTRL_MSG_BASE + 0x01
#define EC_WM_INVALIDATED			EDIT_CTRL_MSG_BASE + 0x02
#define EC_WM_CHANGE_CARET_POS		EDIT_CTRL_MSG_BASE + 0x03
#define EC_WM_SCROLL				EDIT_CTRL_MSG_BASE + 0x04
#define EC_WM_KILLFOCUS				EDIT_CTRL_MSG_BASE + 0x05
#define EC_WM_SETFOCUS				EDIT_CTRL_MSG_BASE + 0x06
#define EC_WM_CHANGE_SELECTED_TEXT	EDIT_CTRL_MSG_BASE + 0x07
#define EC_WM_PASTE_TEXT			EDIT_CTRL_MSG_BASE + 0x08

#define EC_WM_INVALIDATE			EDIT_CTRL_MSG_BASE + 0x10
#define EC_WM_INVALIDATE_EDITDATA	EDIT_CTRL_MSG_BASE + 0x11
#define EC_WM_INVALIDATE_ROW		EDIT_CTRL_MSG_BASE + 0x12
#define EC_WM_INVALIDATE_ROWS		EDIT_CTRL_MSG_BASE + 0x13
#define EC_WM_INVALIDATE_ROW_HEADER		EDIT_CTRL_MSG_BASE + 0x14
#define EC_WM_INVALIDATE_COL_HEADER		EDIT_CTRL_MSG_BASE + 0x15
#define EC_WM_REDRAW				EDIT_CTRL_MSG_BASE + 0x16

#define EC_WM_NOTICE_UPDATE			EDIT_CTRL_MSG_BASE + 0x17

#define EC_WM_REDRAW_ALLWND			EDIT_CTRL_MSG_BASE + 0x20


// GridCtrl
#define GRID_CTRL_MSG_BASE			WM_APP + 0x0300

#define GC_WM_CHANGE_CELL_POS		GRID_CTRL_MSG_BASE + 0x01
#define GC_WM_CHANGE_SELECT_AREA	GRID_CTRL_MSG_BASE + 0x02
#define GC_WM_UPDATE_GRID_DATA		GRID_CTRL_MSG_BASE + 0x03
#define GC_WM_KILLFOCUS				GRID_CTRL_MSG_BASE + 0x05
#define GC_WM_SETFOCUS				GRID_CTRL_MSG_BASE + 0x06

#define GC_WM_UPDATE				GRID_CTRL_MSG_BASE + 0x10
#define GC_WM_INVALIDATE			GRID_CTRL_MSG_BASE + 0x11
#define GC_WM_INVALIDATE_CELL		GRID_CTRL_MSG_BASE + 0x12
#define GC_WM_INVALIDATE_ROW		GRID_CTRL_MSG_BASE + 0x13
#define GC_WM_INVALIDATE_ROW_HEADER	GRID_CTRL_MSG_BASE + 0x14
#define GC_WM_INVALIDATE_RANGE		GRID_CTRL_MSG_BASE + 0x15
#define GC_WM_INVALIDATE_TOP_LEFT	GRID_CTRL_MSG_BASE + 0x16
#define GC_WM_INVALIDATE_CELL_HEADER	GRID_CTRL_MSG_BASE + 0x17
#define GC_WM_DBL_CLK_COL_HEADER	GRID_CTRL_MSG_BASE + 0x40
#define GC_WM_CLEAR_ACTIVE_WND_FLG	GRID_CTRL_MSG_BASE + 0x50
#define GC_WM_EDIT_KEY_DOWN			GRID_CTRL_MSG_BASE + 0x90


// CancelDlg
#define CANCEL_DLG_MSG_BASE			WM_APP + 0x0400

#define CND_WM_EXIT					CANCEL_DLG_MSG_BASE + 0x01
#define CND_WM_STATIC				CANCEL_DLG_MSG_BASE + 0x02
#define CND_WM_QUERY_CANCEL			CANCEL_DLG_MSG_BASE + 0x03
#define CND_WM_SETRANGE				CANCEL_DLG_MSG_BASE + 0x04
#define CND_WM_SETPOS				CANCEL_DLG_MSG_BASE + 0x05
#define CND_WM_STEPIT				CANCEL_DLG_MSG_BASE + 0x06
#define CND_WM_SET_ROW_CNT			CANCEL_DLG_MSG_BASE + 0x90

// FileTabCtrl
#define FILE_TAB_CTRL_MSG_BASE	WM_APP + 0x0500

#define TC_MCLICK		FILE_TAB_CTRL_MSG_BASE + 0x01
#define TC_MOVE_TAB		FILE_TAB_CTRL_MSG_BASE + 0x02
#define TC_CLOSE_BTN	FILE_TAB_CTRL_MSG_BASE + 0x03
#define TC_TOOL_TIP_NAME	FILE_TAB_CTRL_MSG_BASE + 0x04

// CodeAssistWnd
#define CODE_ASSIST_WND_MSG_BASE	WM_APP + 0x510
#define CAW_WM_DBLCLICK		CODE_ASSIST_WND_MSG_BASE + 0x01
#define CAW_WM_ACTIVATEAPP	CODE_ASSIST_WND_MSG_BASE + 0x02

// ParamAssistWnd
#define PARAM_ASSIST_WND_MSG_BASE	WM_APP + 0x510
#define PAW_WM_ACTIVATEAPP	CODE_ASSIST_WND_MSG_BASE + 0x02

// WheelSplitterWnd
#define WHEEL_SPLITTER_WND_MSG_BASE	WM_APP + 0x530
#define WSW_WM_WHEEL_TRANSFER_MSG	WHEEL_SPLITTER_WND_MSG_BASE + 0x01

#endif __OCTRL_MSG_H_INCLUDED__

