//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// psqlgrid.rc で使用
//
#define IDC_BTN_BOTTOM                  3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PSQLGRTYPE                  129
#define IDD_LOGIN                       130
#define IDD_TABLE_LIST_DLG              131
#define IDD_CANCEL_DLG                  132
#define IDD_SEARCH_DLG                  133
#define IDD_OPT_SETUP                   134
#define IDD_REPLACE_DLG                 135
#define IDD_INSERT_ROWS_DLG             136
#define IDR_EDIT_MENU                   137
#define IDB_DATA_LOCK                   138
#define IDD_DATA_EDIT_DLG               139
#define IDR_DUMMY                       140
#define IDD_INPUT_SEQUENCE_DLG          142
#define IDD_ACCELERATOR_DLG             155
#define IDR_GRID_CALC_MENU              158
#define IDD_SHORTCUT_KEY_DLG            162
#define IDD_OPT_GRID                    166
#define IDD_GRID_SORT_DLG               175
#define IDD_CONNECT_INFO_DLG            176
#define IDD_GRID_FILTER_DLG             217
#define IDR_OBJECTBAR_FILTER_MENU       333
#define IDC_STATIC0                     1003
#define IDC_STATIC1                     1006
#define IDC_COLUMN_LIST                 1007
#define IDC_TABLE_LIST                  1008
#define IDC_BUTTON_SELECT_ALL_COLUMN    1010
#define IDC_STATIC_TABLE                1012
#define IDC_STATIC_COLUMN               1014
#define IDC_STATIC_WHERE                1015
#define IDC_EDIT_ROW_CNT                1016
#define IDC_STATIC_FILTER               1018
#define IDC_STATIC_OWNER                1019
#define IDC_CHECK_ADJUST_COL_WIDTH      1020
#define IDC_SELECTED_COLUMN_LIST        1021
#define IDC_CHECK_PUT_COLUMN_NAME       1022
#define IDC_CHECK_DATA_LOCK             1023
#define IDC_BTN_SAVE                    1024
#define IDC_CHECK_REGISTER_SHELL        1025
#define IDC_BTN_LOAD                    1026
#define IDC_CHECK_USE_MESSAGE_BEEP      1027
#define IDC_EDIT_FILTER                 1029
#define IDC_CHECK_USE_USER_UPDATABLE_COLUMNS 1031
#define IDC_BTN_FILTER                  1033
#define IDC_CHECK_SHARE_CONNECT_INFO    1034
#define IDC_BUTTON_ADD                  1035
#define IDC_CHECK_EDIT_OTHER_OWNER      1035
#define IDC_CHECK_DISP_ALL_DELETE_NULL_ROWS_WARNING 1036
#define IDC_BUTTON_DEL                  1037
#define IDC_BUTTON_CLEAR_COLUMN_LIST    1038
#define IDC_SPIN_SELECTED_COLUMN        1039
#define IDC_EDIT_START_NUM              1042
#define IDC_EDIT_INCREMENTAL            1043
#define IDC_COMBO_NLS_DATE_FORMAT       1048
#define IDC_COMBO_NLS_TIMESTAMP_FORMAT  1049
#define IDC_EDIT_INITIAL_DIR            1050
#define IDOK2                           1051
#define IDC_COMBO_LINE_TYPE             1052
#define IDC_BTN_INITIAL_DIR             1053
#define IDC_CHECK_SHOW_SPACE            1054
#define IDC_BTN_ADD                     1071
#define IDC_COMBO_SEARCH_TEXT           1900
#define ID_BTN_NEXT                     1901
#define ID_BTN_PREV                     1902
#define IDC_CHECK_DISTINCT_LWR_UPR      1903
#define IDC_CHECK_REGEXP                1904
#define IDC_COMBO_REPLACE_TEXT          1905
#define IDC_CHECK_DISTINCT_WIDTH_ASCII  1905
#define ID_BTN_REPLACE                  1906
#define ID_BTN_REPLACE_ALL              1907
#define IDC_RADIO_SELECTED_AREA         1908
#define IDC_RADIO_ALL                   1909
#define IDC_CHECK_DISTINCT_WIDTH_ASCII2 1910
#define IDC_EDIT_USER                   2000
#define IDC_EDIT_PASS                   2002
#define IDC_EDIT_HOST                   2006
#define IDC_EDIT_DB_NAME                2007
#define IDC_EDIT_PORT                   2008
#define IDC_EDIT_PORT_NO                2009
#define IDC_LIST1                       2010
#define IDC_EDIT_OPTION                 2011
#define IDC_EDIT_CONNECT_NAME           2012
#define IDC_BTN_UP                      2013
#define IDC_EDIT_NEW_KEY                2018
#define IDC_BTN_DOWN                    2020
#define IDC_BTN_DEL                     2024
#define IDC_BTN_COPY                    2025
#define ID_BTN_ADD                      2026
#define IDC_EDIT_PASSWD                 2028
#define IDC_BTN_DELETE                  2030
#define IDC_STATIC_URL                  2031
#define IDC_EDIT_LONG_READ_BUF_SIZE     2043
#define IDC_EDIT_CLOB_READ_BUF_SIZE     2044
#define IDC_BTN_DEFAULT_COLOR           2057
#define IDC_CHECK_SHOW_2BYTE_SPACE      2080
#define IDC_CHECK_SHOW_LINE_FEED        2081
#define IDC_CHECK_SHOW_TAB              2082
#define IDC_COMBO_NLS_TIMESTAMP_FORMAT_TZ 2085
#define IDC_COMBO_TIMEZONE              2086
#define IDC_LIST_CATEGORY               2098
#define IDC_LIST_COMMAND                2100
#define IDC_LIST_ACCEL                  2101
#define IDC_BTN_DEFAULT                 2102
#define IDC_STATIC_CURRENT_MENU         2103
#define IDC_STATIC_VERSION              2108
#define IDC_BTN_GRID_BG_COLOR           2140
#define IDC_BTN_GRID_HEADER_BG_COLOR    2141
#define IDC_BTN_GRID_SELECT_COLOR       2142
#define IDC_BTN_GRID_NULL_CELL_COLOR    2143
#define IDC_BTN_GRID_LINE_COLOR         2144
#define IDC_BTN_GRID_TEXT_COLOR         2145
#define IDC_BTN_GRID_MARK_COLOR         2146
#define IDC_BTN_GRID_INSERT_COLOR       2147
#define IDC_BTN_GRID_UPDATE_COLOR       2148
#define IDC_BTN_GRID_DELETE_COLOR       2149
#define IDC_BTN_GRID_SEARCH_COLOR       2150
#define IDC_BTN_GRID_HEADER_LINE_COLOR  2151
#define IDC_SET_LOGIN_INFO              2205
#define IDC_CHECK_ADJUST_COL_WIDTH_NO_USE_COLNAME 2206
#define IDC_CHECK_INVERT_SELECT_TEXT    2207
#define IDC_CHECK_COPY_ESCAPE_DBLQUOTE  2209
#define IDC_CHECK_IME_CARET_COLOR       2210
#define IDC_CHECK_END_KEY_LIKE_EXCEL    2211
#define IDC_COMBO_SORT_KEY1             2212
#define IDC_RADIO_ORDER_ASC1            2213
#define IDC_RADIO_ORDER_DESC1           2214
#define IDC_COMBO_SORT_KEY2             2216
#define IDC_RADIO_ORDER_ASC2            2217
#define IDC_RADIO_ORDER_DESC2           2218
#define IDC_COMBO_SORT_KEY3             2219
#define IDC_RADIO_ORDER_ASC3            2220
#define IDC_RADIO_ORDER_DESC3           2221
#define IDC_CHECK_LINE_MODE_RIGHT       2345
#define IDC_COMBO_GRID_COLUMN           2407
#define ID_BTN_FILTER_RUN               2408
#define IDC_EDIT_CELL_PADDING_TOP       2412
#define IDC_EDIT_CELL_PADDING_BOTTOM    2413
#define IDC_EDIT_CELL_PADDING_LEFT      2414
#define IDC_EDIT_CELL_PADDING_RIGHT     2415
#define IDC_EDIT_DBNAME                 3000
#define IDC_STATIC_LINE_TYPE            3000
#define IDC_EDIT_NULL_TEXT              5000
#define IDC_COMBO_OWNER                 5001
#define ID_SET_FONT                     32771
#define ID_SAVE_CLOSE                   32772
#define ID_DELETE_ROW                   32773
#define ID_INSERT_ROW                   32775
#define ID_SELECT_TABLE                 32776
#define ID_ENTER_EDIT                   32780
#define ID_INPUT_ENTER                  32781
#define ID_SEARCH                       32783
#define ID_ADJUST_ALL_COL_WIDTH         32785
#define ID_OPTION                       32786
#define ID_INSERT_ROWS                  32787
#define ID_SET_LOGIN_INFO               32788
#define ID_FILE_SAVE_GRID_AS            32789
#define ID_REPLACE                      32790
#define ID_SEARCH_NEXT                  32794
#define ID_SEARCH_PREV                  32795
#define ID_GRID_COPY_TAB                32840
#define ID_GRID_COPY_TAB_CNAME          32841
#define ID_GRID_COPY_CSV                32842
#define ID_GRID_COPY_CSV_CNAME          32843
#define ID_GRID_COPY_FIX_LEN            32844
#define ID_GRID_COPY_FIX_LEN_CNAME      32845
#define ID_TO_LOWER                     32900
#define ID_TO_UPPER                     32901
#define ID_RECONNECT                    32921
#define ID_EQUAL_ALL_COL_WIDTH          32938
#define ID_CLEAR_SEARCH_TEXT            32940
#define ID_ACCELERATOR                  32945
#define ID_HANKAKU_TO_ZENKAKU           33499
#define ID_ZENKAKU_TO_HANKAKU           33500
#define ID_HANKAKU_TO_ZENKAKU_KATA      33501
#define ID_HANKAKU_TO_ZENKAKU_ALPHA     33502
#define ID_ZENKAKU_TO_HANKAKU_KATA      33503
#define ID_ZENKAKU_TO_HANKAKU_ALPHA     33504
#define ID_DELETE_NULL_ROWS             34000
#define ID_EDIT_PASTE_TO_CELL           34001
#define ID_DATA_EDIT                    34002
#define ID_UPLOAD_LOB_DATA              34003
#define ID_DELETE_ALL_NULL_ROWS         34004
#define ID_SET_NULL_LOB_DATA            34005
#define ID_INPUT_SEQUENCE               34006
#define ID_UPDATE_BFILE                 34007
#define ID_ADJUST_ALL_COL_WIDTH_DATAONLY 35228
#define ID_ADJUST_ALL_COL_WIDTH_USE_COLNAME 35229
#define ID_DOWNLOAD_LOB_DATA            35238
#define ID_GRID_CALC_TYPE_TOTAL         35240
#define ID_GRID_CALC_TYPE_AVE           35241
#define ID_GRID_CALC_TYPE_MAX           35242
#define ID_GRID_CALC_TYPE_MIN           35243
#define ID_GRID_CALC_TYPE_NONE          35244
#define ID_GRID_SORT                    35250
#define ID_SEARCH_COLUMN                35256
#define ID_GRID_SWAP_ROW_COL            35265
#define ID_FILTER_CLEAR                 35298
#define ID_DATA_SET_NULL                38000
#define ID_DATA_SET_BLANK               38001
#define ID_SET_DATA_BLANK               38002
#define ID_GRID_FILTER_ON               38003
#define ID_GRID_FILTER_OFF              38004
#define ID_OBJECTBAR_FILTER_ADD         38005
#define ID_OBJECTBAR_FILTER_DEL         38006
#define ID_OBJECTBAR_FILTER_CLEAR       38007
#define ID_EDIT_DELETE                  38008
#define ID_SELECT_ALL                   38009
#define ID_GRID_COLUMN_WIDTH            38010
#define ID_SHOW_CREDITS                 38011
#define AFX_IDS_APP_TITLE2              57346
#define AFX_IDS_IDLEMESSAGE2            57347
#define ID_INDICATOR_CURSOR_POS         59143
#define ID_INDICATOR_SESSION_INFO       59144
#define ID_INDICATOR_DATA_LOCK          59145
#define ID_INDICATOR_GRID_CALC          59146
#define ID_INDICATOR_END                59147

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         38012
#define _APS_NEXT_CONTROL_VALUE         5002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
